name: Firebase Deploy

on:
  push:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.12.1
      - name: Install Dependencies
        run: npm ci
      - name: Build `client` application
        run: npm run build
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          ET_PROJECT_ID: ${{ secrets.ET_PROJECT_ID }}
          ET_APP_ID: ${{ secrets.ET_APP_ID }}
          ET_STORAGE_BUCKET: ${{ secrets.ET_STORAGE_BUCKET }}
          ET_API_KEY: ${{ secrets.ET_API_KEY }}
          ET_AUTH_DOMAIN: ${{ secrets.ET_AUTH_DOMAIN }}
          ET_MESSAGING_SENDER_ID: ${{ secrets.ET_MESSAGING_SENDER_ID }}
          ET_MEASUREMENT_ID: ${{ secrets.ET_MEASUREMENT_ID }}
